In [1]:
import numpy as np
import numpy.ma as ma

First I'll make a couple test arrays, one to represent the number density, and one to represent the temperature. Both have the same shape.

In [2]:
n = np.ones((3,3,3))
print(n)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [3]:
T = np.arange(0,27).reshape((3,3,3))

In [4]:
print(np.shape(n), np.shape(T))

(3, 3, 3) (3, 3, 3)


Now I want to create a mask, where all of the places in the array that match my given condition are False. This is basically what you did when you made your True/False array with logical and, except backwards. There may be a more efficient way to do this using some other mask functions, but this seems to work okay - I create a new version of the temperature array with the appropriate mask using "masked_outside", and then get the mask itself using "getmask".

In [5]:
mid_T = ma.masked_outside(T, 5, 15)

In [6]:
mid_T_mask = ma.getmask(mid_T)
print(mid_T_mask)

[[[ True  True  True]
  [ True  True False]
  [False False False]]

 [[False False False]
  [False False False]
  [False  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]]


Before I actually apply the mask, I want to make sure that I make a copy of the original number density array. That's because I'm going to be setting a bunch of values to 0 based on my temperature condition, and I want to be able to make a different copy for a different temperature range. So here, you'd have something like n_FeII, instead of n_mid_T.

In [7]:
n_mid_T = n.copy()

Now we actually apply the mask, by setting all values to 0 where the mask is.

In [8]:
n_mid_T[mid_T_mask] = 0

And the result is an array that only has positive values of density where the temperature met the criterion, great!

In [9]:
print(n_mid_T)

[[[0. 0. 0.]
  [0. 0. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [10]:
print(np.shape(n), np.shape(n_mid_T), np.shape(mid_T_mask))

(3, 3, 3) (3, 3, 3) (3, 3, 3)


Everything has the same shape, awesome, so you can then go use all the same functions you were using before to get the column density, for example.

In [11]:
n_midT_col = np.sum(n_mid_T, axis=1)

In [13]:
print(n_midT_col)

[[1. 1. 2.]
 [3. 2. 2.]
 [0. 0. 0.]]
